name: Hourly Config Updater

permissions:
  contents: write

on:
  schedule:
    - cron: '0 * * * *'  # هر ساعت اجرا میشه (UTC)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run updater script
        run: python updater.py

      - name: Upload VIP.txt as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: VIP-txt-output
          path: VIP.txt

      - name: Commit & push changes if any
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add VIP.txt || true
          if ! git diff --quiet; then
            git commit -m "Auto-update configs (hourly)"
            git push
          else
            echo "No changes to commit."
          fi
